config/routes.rb
Crowdfunder::Application.routes.draw do

  get "sessions/new"

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup" 
 
  resources :users, :except => [:index]
  resources :sessions

  get "welcome/index"

  resources :projects do
    resources :pledges, :only => [:new, :create]
  end

  namespace :my do
    resources :projects
  end

  root to: 'welcome#index' 

end

app/models/pledge.rb
class Pledge < ActiveRecord::Base
  attr_accessible :amount, :project_id, :user_id
  belongs_to :user
  belongs_to :project 

  validates :amount, :numericality => { :greater_than => 0 }
  validates :user_id, presence: true
  validates :project_id, presence: true
end

app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :user 
  attr_accessible :description, :goal, :teaser, :title, :user_id
  has_many :pledges

  validates :title, presence: true, length: {maximum: 100}
  validates :teaser, presence: true, length: {maximum: 255}
  validates :description, presence: true
  validates :goal, presence: true, numericality: {greater_than: 0, allow_blank: true}
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  attr_accessible :first_name, :last_name, :email, :password, :password_confirmation
  has_many :projects
  has_many :pledges

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true
  validates :password, presence: true

  validates_confirmation_of :password, :message => "should match confirmation", :if => :password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :nav_state

  def nav_state
  	# to be overwritten by controllers
  end
  
  protected

  def not_authenticated
  	redirect_to new_session_path, :alert => "Please login first"
  end
end

app/controllers/my/projects_controller.rb
class My::ProjectsController < ApplicationController
	before_filter :require_login
	before_filter :require_project, except: [:index, :new, :create]


	def index
		@projects = current_user.projects.order('projects.created_at DESC').all
	end

	def new
		@project = current_user.projects.build
	end

	def edit
	end

	def update
		if @project.update_attributes params[:project]
			redirect_to [:my, :projects], notice: "Project updated!"
		else
			render :edit
		end
	end

	def create
		@project = current_user.projects.create params[:project]

		if @project.save
			redirect_to [:my, :projects], notice: "Project created!"
		else
			render :new
		end
	end

	def nav_state
		@nav = :my_projects
	end

	protected

	def require_project
		@project = current_user.projects.find params[:id]
	end
end

app/controllers/pledges_controller.rb
class PledgesController < ApplicationController
	before_filter :require_login
	before_filter :require_project

	def new
		@pledge = @project.pledges.build
	end

	def create
		@pledge = @project.pledges.build params[:pledge]
		@pledge.user = current_user

		if @pledge.save
			UserMailer.new_pledge(@pledge).deliver
			redirect_to @project, notice: "Nice! Thanks for pledging $#{@pledge.amount} to this project!"
		else
			render :new
		end
	end

	protected
	def require_project
		@project = Project.find params[:project_id]
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
  	@project = Project.order('projects.created_at DESC').page(params[:page]).per(8)
  end

  def show
  	@project = Project.find(params[:id])
  end

  def nav_state
  	@nav = :projects
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = login(params[:email], params[:password], params[:remember_me])
    	if user
    		redirect_to root_url, :notice => "Logged In!"
    	else
    		flash.now.alert = "Email or password was Invalid"
        render :new
    	end
  end

  def destroy
  	logout
  	redirect_to root_url, :notice => "Bye!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(params[:user])
  	if @user.save 
      auto_login(@user)
  		redirect_to root_url, :notice => "Account Created!"
  	else
  		render :new
  	end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def nav_state
  	@nav = :home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/my/projects_helper.rb
module My::ProjectsHelper
end

app/helpers/pledges_helper.rb
module PledgesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crowdfunder</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/shared/nav' %>

<div class='flash-alerts'>
	<% if flash[:alert] %>
		<p id="alert"><%= flash[:alert] %></hp>
	<% end %>
	<% if flash[:notice] %>
		<p id="notice"><%= flash[:notice] %></p>
	<% end %>
</div>
<div class="container">
<%= yield %>
</div>
</body>
</html>

app/views/layouts/shared/_nav.html.erb
<div class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<a class="brand" href="#">Crowdfunder</a>
			<div class="nav-collapse collapse">
					<ul class="nav">
						<li class="<%= 'active' if @nav == :home %>"><%= link_to 'Home', :root %></li>
						<li class="<%= 'active' if @nav == :projects %>">
							<%= link_to 'Projects', :projects %></li>
						<% if logged_in? %>
							<li class="divider-vertical"></li>
						  <li class="<%= 'active' if @nav == :my_projects %>">
						    <%= link_to 'My Projects', [:my, :projects] %><li>
						<% end %>
					</ul>
					<div class="pull-right">
						<% if logged_in? %>
							<%= link_to 'Log Out', logout_path, class: 'btn btn-warning' %>
						<% else %>
							<%= link_to 'Log In', new_session_path, class: 'btn btn-success' %>
							<%= link_to 'Sign Up', [:new, :user], class: 'btn btn-primary' %>
						<% end %>
					</div>

			</div>
		</div>
	</div>
</div>

app/views/my/projects/create.html.erb
create.html.erb

app/views/my/projects/edit.html.erb
<h1>Edit this project!</h1>

<%= form_for [:my, @project] do |f| %>
	<div class="field">
		<%= f.label :title %>
		<%= f.text_field :title %>
	</div>
	<div class="field">
		<%= f.label :teaser %>
		<%= f.text_field :teaser %>
	</div>
	<div class="field">
		<%= f.label :description %>
		<%= f.text_area :description %>
	</div>
	<div class="field">
		<%= f.label :goal %>
		<%= f.number_field :goal %>
	</div>
	<%= f.submit "Publish Project" %>
<% end %>

app/views/my/projects/index.html.erb
<h1>My Projects</h1>

	<% @projects.each do |project| %>
	<p>Project Name: <%= link_to project.title, project %></p>
	<% end %>	

	<%= link_to "Create a new project", new_my_project_path, class: "btn btn-success" %>

app/views/my/projects/new.html.erb
<h1>Create a new project!</h1>

<%= form_for [:my, @project] do |f| %>
	<div class="field">
		<%= f.label :title %>
		<%= f.text_field :title %>
	</div>
	<div class="field">
		<%= f.label :teaser %>
		<%= f.text_field :teaser %>
	</div>
	<div class="field">
		<%= f.label :description %>
		<%= f.text_area :description %>
	</div>
	<div class="field">
		<%= f.label :goal %>
		<%= f.number_field :goal %>
	</div>
	<%= f.submit "Publish Project" %>
<% end %>

app/views/pledges/create.html.erb
create.html.erb

app/views/pledges/new.html.erb
<h1>New Pledge</h1>
 
<%= form_for [@project, @pledge] do |f| %>
	 <div class="field">
	 	<%= f.label :amount %>
	 	<%= f.number_field :amount %>
	 </div>
	 <div class="action">
	 	<%= f.submit "Pledge Now" %>
	 </div>
<% end %>

app/views/projects/index.html.erb
<h1>Listing Projects</h1>

	<% @project.each do |project| %>
	<ul>
		<li class="project"><%= link_to project.title, project %><br>
				<%= project.teaser %></li>
	</ul>
	<% end %>	
	<%= paginate @project %>

app/views/projects/show.html.erb
<h1><%= @project.title %></h1>
<p>A project by <%= @project.user.first_name %> <%= @project.user.last_name %></p>

<% if current_user == @project.user %>
	<div>
		<%= link_to "Edit this project", edit_my_project_path, class: 'btn btn-danger' %>
	</div>
<% else %>
<div>
	<%= link_to "Back this project", new_project_pledge_path(@project), class: 'btn btn-info'%>
</div>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<div id="sign_up"><h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <% unless f.object.errors.empty? %>
        <div class="alert alert-error">
          <strong>Try Again! Fix the following things:</strong><br>
          <ul>
            <% f.object.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    </div>
  <% end %>
  <div class="field">
  	<%= f.label :first_name %>
  	<%= f.text_field :first_name %>
  </div>
  <div class="field">
  	<%= f.label :last_name %>
  	<%= f.text_field :last_name %>
  </div>
  <div class="field">
  	<%= f.label :email %>
  	<%= f.text_field :email %>
  </div>
  <div class="field">
  	<%= f.label :password %>
  	<%= f.password_field :password %>
  </div>
  <div class="field">
  	<%= f.label :password_confirmation %>
  	<%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Create Account" %></div>
<% end %>

app/views/welcome/index.html.erb
<h1>Heyho It's Crowdfunder!</h1>
<p align="center"><img src="http://crowdfundpros.com/wp-content/uploads/2013/09/crowd2.jpeg" class="img-polaroid"></p>
<p align="right">Let's fund some crowds, bitches.</p>